apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-env-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-env-cr
rules:
- apiGroups: ["", "compute.crossplane.io", "argoproj.io", "dev.vadasambar.github.io", "container.gcp.crossplane.io"]
  resources: ["secrets", "configmaps", "events", "kubernetesclusters", "applications", "environments", "gkeclusterclasses", "nodepools"]
  verbs: ["*"]

---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-env
subjects:
- kind: ServiceAccount
  name: dev-env-sa 
  namespace: crossplane-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: dev-env-cr
  apiGroup: rbac.authorization.k8s.io
